[package]
name = "workflow"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
clap = { version = "*", features = ["derive"] }
execute = "0.2.9"
handlebars = "4.2.1"
serde_json = "1.0.75"
