[package]
name = "xtask-base"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
clap = { version = "*", features = ["derive"] }
clap_complete = "3.0.4"
duct = "0.13.5"
execute = "0.2.9"
handlebars = "4.2.1"
parse-display = "0.5.3"
serde_json = "1.0.75"
xshell = "0.1.17"
