[package]
name = "xtask-base"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
cargo_metadata.workspace = true
chrono.workspace = true
clap_complete.workspace = true
duct.workspace = true
execute.workspace = true
handlebars.workspace = true
itertools.workspace = true
serde_json.workspace = true
xshell.workspace = true
