name: basic-tests
on: [push, pull_request]
jobs:
  stable-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.73
        profile: minimal
        default: true
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - run: cargo clippy --all-targets -- -D warnings -D clippy::all
    - run: cargo test
    - run: cargo build --all-targets
    - run: cargo doc
    - run: cargo test --benches --tests --release
  stable-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.73
        profile: minimal
        default: true
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - run: cargo clippy --all-targets -- -D warnings -D clippy::all
    - run: cargo test
    - run: cargo build --all-targets
    - run: cargo doc
    - run: cargo test --benches --tests --release
  stable-windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.73
        profile: minimal
        default: true
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - run: cargo clippy --all-targets -- -D warnings -D clippy::all
    - run: cargo test
    - run: cargo build --all-targets
    - run: cargo doc
    - run: cargo test --benches --tests --release
  nightly-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-10-14
        profile: minimal
        default: true
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
    - run: cargo fmt --all -- --check
    - run: cargo install cargo-udeps --locked --version 0.1.43
    - run: cargo udeps --all-targets
